### ISSUE TITLE
nRF Master Control Panel is now called nRF Connect

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-os-5-docs#456]
[bluetooth.md](https://github.com/ARMmbed/Handbook/blob/new_engine/docs/reference/api/connectivity/bluetooth/bluetooth.md) has a reference to nRF Master Control Panel which is now called nRF connect.

Also, I've seen similar references in mbed BLE examples elsewhere.

**Comment by AnotherButler** [comment]
@loverdeg-ep Great catch. 

@pan- Could you please update these? Thanks so much.

**Comment by AnotherButler** [comment]
@loverdeg-ep Have these changes addressed this issue?

**Comment by loverdeg-ep** [comment]
@AnotherButler I'm no longer seeing any references to "nRF Master Control Panel" in the documentation.

I do see references in many of the BLE example readmes but those are outside the scope of this remote.
