### ISSUE TITLE
EventQueue Page Header Links

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-os-5-docs#479]
It could be nice to have some way of navigating beyond the great wall of templates on the [eventQueue](https://os.mbed.com/docs/v5.8/reference/eventqueue.html) page.

**Comment by AnotherButler** [comment]
@geky What's the status of this?

**Comment by AnotherButler** [comment]
@loverdeg-ep I wanted to update you to let you know that this work is still in progress. We hope to complete it as soon as possible.

**Comment by AnotherButler** [comment]
PR up: https://github.com/ARMmbed/mbed-os/pull/7810

**Comment by AnotherButler** [comment]
@loverdeg-ep I'm closing this issue because the PR to solve it merged. Please feel free to reopen it if the PR does not resolve the issue.
