### ISSUE TITLE
Intro to Lora (technology) needs work

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-5-docs#495]
The Lora intro docs has been moved to the Technology section
https://github.com/ARMmbed/Handbook/blob/new_engine/docs/reference/technology/connectivity/intro-to-lora.md

This is great. However, there are parts of the docs that should be moved to Tutorial section, as provide step-by-step instructions on how to do things.

**Comment by AnotherButler** [comment]
Closing because we moved the step-by-step guidance sections to the tutorials book, as requested: https://os.mbed.com/docs/v5.9/tutorials/LoRa-tutorial.html

Thanks again for raising this. 👍 

Please feel free to reopen this if you feel it has not been fully resolved.
