### ISSUE TITLE
memory_tests: fix compiler warnings

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-5-docs#552]
As per discussion in https://github.com/ARMmbed/mbed-cloud-client-example-internal/pull/468

The recommended way to use memory tracing should be tweaked to remove warnings.

https://github.com/ARMmbed/Handbook/blob/new_engine/docs/tutorials/optimize/memory/runtime_mem_trace.md

@AnotherButler @mbartling can you have a lool and maybe involve someone else?

**Comment by AnotherButler** [comment]
@SenRamakri Could you please suggest an engineer who could help with this?

**Comment by deepikabhavnani** [comment]
https://github.com/ARMmbed/mbed-os-5-docs/pull/696 - will fix this.

**Comment by AnotherButler** [comment]
@deepikabhavnani  Because 696 merged, is this OK to close?

**Comment by deepikabhavnani** [comment]
Yes
