### ISSUE TITLE
location & name of toolchain json file

### ISSUE THREAD

**Issue by jflynn129** [ARMmbed/mbed-os-5-docs#595]
QUESTION: I'm looking at and trying to determine:
1. does the 'toolchain profile json' file (https://github.com/ARMmbed/mbed-os-5-docs/blob/new_engine/docs/tools/offline/toolchain_profiles.md) need any special name to be recognized?
2. Does it need to be any special location (./profiles for example)
3. Any available samples (with blinky for example) that show it usage?

I tried adding it to my mbed_app.json file to configure the app build but that doesn't apparently work.

**Comment by jflynn129** [comment]
found it, never mind...

**Comment by AnotherButler** [comment]
@jflynn129 

If you have any further questions, please don't hesitate to ask.
