### ISSUE TITLE
mbed cli - first time user feedback

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-os-5-docs#621]
https://os.mbed.com/forum/helloworld/topic/32269/?page=1#comment-58355 - few questions and how they found answers.

@AnotherButler @ARMmbed/mbed-os-tools Please review

**Comment by AnotherButler** [comment]
Internal ref. IOTDOCS-608

**Comment by AnotherButler** [comment]
Completed with PRs #789, #790 and #791
