### ISSUE TITLE
MBRBlockDevice::partition - type

### ISSUE THREAD

**Issue by deepikabhavnani** [ARMmbed/mbed-os-5-docs#673]
https://github.com/ARMmbed/mbed-os/issues/5506

Query:
I am looking documentation https://os.mbed.com/docs/v5.6/mbed-os-api-doxy/class_m_b_r_block_device.html#ace6dd73e8514a0a2afab8f8bc37bada8

I tried to find supported values/filesystems for type, which is "8-bit partition type to identitfy partition's contents". Would you clarity usage of parameter type with MBRBlockDevice::partition? What are supported values? Is it type same than Partition ID in table https://en.wikipedia.org/wiki/Partition_type#List_of_partition_IDs?

Response:

Yes, the type parameter is an ID from that list:
https://en.wikipedia.org/wiki/Partition_type#List_of_partition_IDs

I didn't include it initially because it's such an unwieldy list (>200 options), but if it helps I can add an enum of the most common types.

I'm also thinking it would be a good idea to just use 0x83 as a default.

Docs Update:
I propose that we clarify mbed-os documentation about usage of partition type.

CC @JaniSuonpera

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-751*

**Comment by AnotherButler** [comment]
@deepikabhavnani Have we updated this in our documentation?

**Comment by deepikabhavnani** [comment]
@AnotherButler - No

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.
