### ISSUE TITLE
build profiles using online compiler

### ISSUE THREAD

**Issue by jflynn129** [ARMmbed/mbed-os-5-docs#704]
When building with the CLI, I am able to specify a "--profile my-profile-file" and modify the build parameters. I see a lot of docs about using the CLI and build-profiles, but I can't seem to find how you specify a build profile for the online compiler.  Is there some method to specify the compile and link parameters when using the online compiler?

**Comment by jflynn129** [comment]
@dlfryar

**Comment by AnotherButler** [comment]
@jflynn129 The Online Compiler uses the develop profile. You can find some information about this here: https://os.mbed.com/docs/v5.9/tools/build-profiles.html

**Comment by theotherjimmy** [comment]
That's correct ATM. A user cannot modify the build profile.

**Comment by jflynn129** [comment]
Ok, thanks for the confirmation. I'll steer customers toward the CLI only for the example I distribute.
