### ISSUE TITLE
Pelion Device Management Client required for mbed dm functionality

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/mbed-os-5-docs#707]
The current documentation for the `mbed dm` command makes no mention of Pelion Device Management Client (PDMC). 

https://github.com/ARMmbed/mbed-os-5-docs/blob/development/docs/tools/offline/cli-device-management.md

In order for someone to use the `mbed dm` command to update a device,their device must be running an application with PDMC and a supported managed or unmanaged bootloader.

Documentation needs to mention that this command only works for devices running Pelion Device Management Client and the application is combined with a bootloader. Additionally, you may want to have a line similar to:

"To test this feature, you can run the [Pelion Device Management Client Example](https://github.com/ARMmbed/mbed-cloud-client-example) on one of our reference platforms."

**Comment by dhwalters423** [comment]
One more suggestion related to this, we should mention that the device needs to be running the `<name of app>_update.bin` first. So in the tutorial we should say

1. run `mbed dm init` command
2. `mbed compile ...`
3. Flash device with `<name_of_app_update.bin>`
5. View serial terminal for device id
4.  `mbed dm update device -D <device ID> -m <target>`
6.  View serial terminal for update progress

**Comment by ashok-rao** [comment]
@kegilbert / @AnotherButler : Could you please address this? Thanks.

**Comment by kegilbert** [comment]
I'm double checking with some cloud/pelion people, I can update the docs accordingly.

**Comment by oliverjharper** [comment]
@teetak01 - any chance you could help with @AnotherButler question above?

**Comment by AnotherButler** [comment]
@teetak01 Do you agree with @dhwalters423 that we need to specify which binary one uses to flash the device first that contains the bootloader, and which binary one uses for an update? If so, could you please help me clarify that?

**Comment by teetak01** [comment]
The "default" binary should be flashed to the board. Then the "_update.bin" is automatically used by mbed-cli for firmware update, but if customer wants to provide the bin explicitly, it should be the _update.bin.
