### ISSUE TITLE
"the porting guide" link gives 404 from Bootloader page

### ISSUE THREAD

**Issue by SamiLappalainenArm** [ARMmbed/mbed-os-5-docs#709]
Steps:
1) go to https://os-doc-builder.test.mbed.com/docs/development/porting/bootloader.html
2) open "You can learn to port the Update Client bootloader to new targets in the porting guide." link
3) "404 Not found" is shown from url https://cloud.mbed.com/docs/current/porting/porting-the-update-client.html

**Comment by AnotherButler** [comment]
@MelindaWeed Could you please fix this link?

**Comment by AnotherButler** [comment]
@SamiLappalainenArm Thanks for raising this. This issue has been resolved with PR #727
