### ISSUE TITLE
[5.10-OOB] Add type with device at NFC EEPROM driver porting guide

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-5-docs#713]
**device** used in **[NFC EEPROM driver porting guide](https://github.com/ARMmbed/mbed-os-5-docs/blob/24f801d322b92323a5b4b1f3efcb0bbf9520684e/docs/reference/contributing/connectivity/NFCEEPROMDriver.md)** is not clear. 
For easy understanding, please add type as **device (NFC tag)** or **device (NFC reader/writer)**

**Comment by AnotherButler** [comment]
@soramame21 Thanks for letting us know. Could you please work with @donatieng to put up a PR to fix this?

**Comment by AnotherButler** [comment]
@pan- Could you please look into this?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-749*

**Comment by AnotherButler** [comment]
ping @pan-

**Comment by AnotherButler** [comment]
ping @pan- @donatieng

**Comment by AnotherButler** [comment]
I'm going to close this issue due to lack of movement. Please feel free to reopen if it's still relevant.
