### ISSUE TITLE
"Mbed CLI" link from "Adding and configuring targets" gives 404

### ISSUE THREAD

**Issue by SamiLappalainenArm** [ARMmbed/mbed-os-5-docs#716]
steps:
1) go to https://os-doc-builder.test.mbed.com/docs/development/tools/adding-and-configuring-targets.html
2) open Mbed CLI link from "Note: The Online Compiler does not support this functionality. You need to use Mbed CLI to take your code offline."
3) Not found from url "https://os-doc-builder.test.mbed.com/docs/development/tools/arm-mbed-cli.html" is shown

**Comment by AnotherButler** [comment]
Thanks @SamiLappalainenArm 👍 
Resolved by PR #731
