### ISSUE TITLE
")." missing from text

### ISSUE THREAD

**Issue by SamiLappalainenArm** [ARMmbed/mbed-os-5-docs#717]
1) go to url: https://os-doc-builder.test.mbed.com/docs/development/tools/adding-and-configuring-targets.html
2) ")." is missing from "We use the tool ArmPackManager to parse CMSIS Packs for target information. index.json stores the parsed information from the PDSC (Pack Description"

**Comment by AnotherButler** [comment]
Resolved by PR #730
