### ISSUE TITLE
using link "target configuration" from Mbed OS build rules gives 404

### ISSUE THREAD

**Issue by SamiLappalainenArm** [ARMmbed/mbed-os-5-docs#722]
1) go to url: https://os-doc-builder.test.mbed.com/docs/development/tools/mbed-os-build-rules.html
2) try to open link from "The Mbed OS build tools use the target configuration found in targets.json, mbed_app.json and mbed_lib.json as input to these rules."
=> 404 is shown from url: https://os-doc-builder.test.mbed.com/docs/development/tools/mbed_targets.md

**Comment by AnotherButler** [comment]
@SamiLappalainenArm Thanks for raising this. It's now resolved by PR #728
