### ISSUE TITLE
"mbed-os blockdevice api" link gives 404

### ISSUE THREAD

**Issue by SamiLappalainenArm** [ARMmbed/mbed-os-5-docs#723]
1) goto url https://cloud.mbed.com/docs/current/porting/update-k64f-port.html
2) open link "This uses the mbed-os blockdevice api to store the candidate firmware and header." from "pal-blockdevice" section

=> 404 is shown from url: https://github.com/ARMmbed/mbed-os/blob/master/features/filesystem/bd/BlockDevice.h

**Comment by AnotherButler** [comment]
Thanks @SamiLappalainenArm 
PR up: https://github.com/ARMmbed/mbed_Cloud_Docs/pull/963
