### ISSUE TITLE
Link Mbed storage configuration example to storage reference guide

### ISSUE THREAD

**Issue by jussisip** [ARMmbed/mbed-os-5-docs#829]
Could we add web site link of storage application configuration example (https://cloud.mbed.com/docs/current/connecting/mbed-os-storage-configuration.html) into Mbed OS storage reference documentation site https://os.mbed.com/docs/v5.10/reference/configuration-storage.html 

In other words:
The reader of Mbed storage reference documentation
https://os.mbed.com/docs/v5.10/reference/configuration-storage.html

Would benefit to have link into https://cloud.mbed.com/docs/current/connecting/mbed-os-storage-configuration.html
since it provides additional information about how the storage application could be configured.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-748*

**Comment by AnotherButler** [comment]
Please review PR 865
