### ISSUE TITLE
Dead Link provisioning-sdk.html

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-os-5-docs#850]
## Page link

https://os.mbed.com/docs/v5.10/evaluation-production/stage-4-pilot.html

![image](https://user-images.githubusercontent.com/24318071/49093785-db84cc00-f232-11e8-8e7e-fb0769bbd1b5.png)

## Expected to find...

Working link to provisioning-sdk

## Found

404 Error

https://cloud.mbed.com/docs/latest/introduction/provisioning-sdk.html

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-807*

**Comment by iriark01** [comment]
Fixed; will be built soon. Thank you.
