### ISSUE TITLE
Incorrect URL to configure local debug toolchain

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-5-docs#860]
## Incorrect URL to configure local debug toolchin

https://os.mbed.com/docs/v5.10/tutorials/eclipse.html#importing-the-project-in-eclipse

In the OpenOCD setting, I found:

> - Under *OpenOCD Setup*, set the *Config options* to the setup options from the [Configure your local debug toolchain](https://os.mbed.com/docs/development/tools/exporting.html) guide.

But the link points to the exporter.  I think this should be: https://os.mbed.com/docs/v5.10/tools/setting-up-a-local-debug-toolchain.html#openocd

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-820*

**Comment by iriark01** [comment]
Fixed in 5.10 and 5.11 (and development)
