### ISSUE TITLE
Code guidelines: anonymous namespace - enhancement

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-os-5-docs#884]
# Docs issue template

Request comes from https://github.com/ARMmbed/mbed-os/pull/9158 

## Expected to find...

> It might be useful to extend the code guidelines to mention that data structures local to a C++ files should be declared inside an anonymous namespace

## Found

No mention of anonymous namespace

cc @kjbracey-arm @pan- @SenRamakri

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-869*

**Comment by bulislaw** [comment]
@kjbracey-arm @pan- @deepikabhavnani I remember you being involved in some changes to namespaces recently, does anyone want to have a stab at this?

**Comment by AnotherButler** [comment]
@0xc0170 I'm closing this because the PR addressing it has merged. Please reopen if it has not been fully resolved.
